apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

commonLabels:
  project: instavote
  env: dev

commonAnotations:
  supported-by: "me@example.com"

namespace: instavote

