apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

replicas:
  - name: redis
    count: 3

commonLabels:
  project: instavote
  env: dev

commonAnnotations:
  supported-by: "me@example.com"

namespace: instavote

